const PLAYER_IDLE = "PLAYER_IDLE"
const WAITING_PLAYER_PAY = "WAITING_PLAYER_PAY"
const PLAYER_REJECT = "PLAYER_REJECT"
const TRANSACTION_FAILED = "TRANSACTION_FAILED"
const POOR_POOL = "POOR_POOL"
const ROUND_ENDED = "ROUND_ENDED"
const PLAYER_WIN = "PLAYER_WIN"
const PLAYER_LOSE = "PLAYER_LOSE"


export default {
  PLAYER_IDLE,
  WAITING_PLAYER_PAY,
  PLAYER_REJECT,
  POOR_POOL,
  TRANSACTION_FAILED,
  ROUND_ENDED,
  PLAYER_WIN,
  PLAYER_LOSE,
}